In [9]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [12]:

feature_data = np.random.randint(0,10,50)
label_data =np.random.randint(0,2,50)
print('원본 data:',feature_data[:10])
print('원본 label:',label_data[:10])

feature_train, feature_test, label_train, label_test_=train_test_split(feature_data, 
                                                             label_data, 
                                                             test_size=0.3, 
                                                             random_state = 42)
print(feature_data)
print(feature_test)
print(label_train)
print(label_test_)

원본 data: [0 2 5 7 1 5 4 9 4 3]
원본 label: [1 1 1 0 0 0 0 0 1 0]
[0 2 5 7 1 5 4 9 4 3 2 3 7 6 6 4 7 3 0 5 3 8 2 2 1 7 8 3 7 4 1 9 1 8 5 6 3
 6 4 7 8 9 8 6 6 9 7 0 1 3]
[6 7 1 9 3 1 8 7 1 5 7 1 6 4 7]
[0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 0]
[0 1 1 0 0 1 1 0 0 1 0 0 1 1 0]
